# Generated by Django 6.0.2 on 2026-02-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_paid_price_sale_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpay',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
    ]
